# Application Name
spring.application.name=kafka-consumer-contas-pagar

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:contas-pagar-consumer-group}
kafka.topic.contas-pagar=${KAFKA_TOPIC_CONTAS_PAGAR:contas-pagar-topic}

# Database Configuration
spring.datasource.url=${CONTASPAGAR_DB_URL:jdbc:postgresql://localhost:5433/contaspagar}
spring.datasource.username=${CONTASPAGAR_DB_USERNAME:postgres}
spring.datasource.password=${CONTASPAGAR_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.danielsmanioto.kafka.consumer=INFO
logging.level.org.springframework.kafka=INFO
