# Application Name
spring.application.name=kafka-consumer-contas-pagar

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=contas-pagar-consumer-group
kafka.topic.contas-pagar=contas-pagar-topic

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/contaspagar
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.danielsmanioto.kafka.consumer=INFO
logging.level.org.springframework.kafka=INFO
